class_name ScriptMerger
extends Node

# This script will take all the files mentionned on
# [script_files] to merge them into an single file called
# [MERGED_FILE_NAME] and located at
# [merged_script_location].

@export var script_files: PackedStringArray = []
@export var merged_script_location: String = "res://"

const MERGED_FILE_NAME: String = "script.gd"
const MERGED_FILE_PREFIX: String = \
	"# This script has been generated by merging multiples\n# files with the ScriptMerger tool all changes on this file\n# will be override by theres files. If you want to modify this\n# code modify directly the script files wich were merged\n"

func _ready():
	var script_path = merged_script_location + MERGED_FILE_NAME
	var script = FileAccess.open(script_path, FileAccess.WRITE)
	script.write(MERGED_FILE_PREFIX)
	script.write("\n")
	for merging_script in script_files:
		# Editor.open_file(merging_script) ?
		script.write(
			"\n#######\n# From: " + 
			merging_script + 
			"\n#######\n"
		)
		var merging_script_access = FileAccess.open(merging_script, FileAccess.READ)
		script.write(merging_script_access.get_text())
		script.write("# eof\n")
	script.save()
	script.close()
	# Editor.open_file(script_path) ?
	set_script(load(script_path))
